### ISSUE TITLE
libopenblas.dll not found

### ISSUE THREAD

**Issue by djerbetian** [libigl/CoMISo#4] opened 2016-03-30 09:02 UTC
Hello,

When I try to run the tutorial 505 or 505, which I managed to compile, the program doesn't start displaying the error: unable to find libpenblas.dll, although I do have it in the folder 
libigl\external\CoMISo\ext\OpenBLAS-v0.2.14-Win64-int64\bin
Any idea ?
![image](https://cloud.githubusercontent.com/assets/5993086/14137143/c8f6004c-f666-11e5-8140-4c48c881bf08.png)

**Comment by danielepanozzo** [comment] 2016-03-31 01:32
There was a bug in the cmake file of libigl. It is fixed now. Please reopen if the problem persists.

**Closed by danielepanozzo** 2016-03-31 01:32 UTC

**Comment by darkpursuer** [comment] 2018-05-04 18:07
I met the same problem when using VS, and I tried to use CoMISo in my project seperately. Could you please show how to fix it in the cmake file?

**Comment by danielepanozzo** [comment] 2018-05-04 20:32
Does it work when you build libigl together with comiso?

**Comment by darkpursuer** [comment] 2018-05-04 20:46
Yes, when I built the solution, it all succeeded. But when I run it, it showed that all the dlls in '_libigl\external\CoMISo\ext\OpenBLAS-v0.2.14-Win64-int64\bin_' was missing

**Comment by danielepanozzo** [comment] 2018-05-04 20:51
I cannot reproduce this on my windows box. Are you compiling all the tutorials at once (using the cmakefile in the tutorials folder, selecting win64 as the compiler? Did you try a clean clone of libigl?

**Comment by darkpursuer** [comment] 2018-05-04 20:57
Eh, I was doing the Computer Graphics project, and I wanted to use libigl and CoMISo in my project. I tried many times but still cannot import the CoMISo successfully. Now I can ensure building my project successfully but not running my project.

I could build the tutorials and run them successfully. So I wonder that whether I can use the way you fixed this issue before to avoid my problem in my project.

**Comment by jdumas** [comment] 2018-05-04 20:59
Maybe you need to copy the comiso dll into the folder of your executable?

**Comment by darkpursuer** [comment] 2018-05-04 21:01
Yes, I can solve this problem by copying them into my executable folder. But how can I import them in my executable folder when using cmake to build my project? Because I cannot upload my executable folder on the Github when submitting my project.

**Comment by danielepanozzo** [comment] 2018-05-04 21:03
The copy happens here:

https://github.com/libigl/CoMISo/blob/master/CMakeLists.txt

There is probably a different path in there. You could cut&paste the part:

```
if(WIN32)
  target_compile_definitions(CoMISo PRIVATE -D_USE_MATH_DEFINES -DNOMINMAX)
  target_compile_options(CoMISo PUBLIC /D_SCL_SECURE_NO_DEPRECATE)
  add_library(CoMISo_blas STATIC IMPORTED)
  set_target_properties(CoMISo_blas PROPERTIES
      IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
      IMPORTED_LOCATION "${CMAKE_CURRENT_SOURCE_DIR}/ext/OpenBLAS-v0.2.14-Win64-int64/lib/libopenblas.dll.a.lib")
  target_link_libraries(CoMISo PRIVATE CoMISo_blas)
endif()
```

and adapt it to your directory structure (after changing the target name).

**Comment by darkpursuer** [comment] 2018-05-07 16:48
Thanks for your help. While I used the part of the code, the problem was still there. 
And did the code shown above invoke the piece of code you mentioned?

**Comment by xarthurx** [comment] 2019-10-25 09:58
I can confirm this bug still exist on Windows 10.
